# Generated by Django 5.0.4 on 2024-04-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='title',
            field=models.CharField(max_length=123, verbose_name='Заголовок'),
        ),
    ]
