# Generated by Django 5.0.4 on 2024-04-11 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_store_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='tags',
        ),
        migrations.DeleteModel(
            name='TagPost',
        ),
    ]
