# Generated by Django 5.0.4 on 2024-04-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_store_cat_remove_store_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='slug',
            field=models.SlugField(blank=True, default=True, max_length=255, verbose_name='слаг'),
        ),
    ]
