# Generated by Django 5.0.4 on 2024-04-13 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_store_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFiles',
        ),
        migrations.AddField(
            model_name='store',
            name='cat_animals',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cat_animals', to='store.category'),
        ),
        migrations.AddField(
            model_name='store',
            name='cat_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cat_type', to='store.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=1280, verbose_name='категория по '),
        ),
    ]
