# Generated by Django 5.0.4 on 2024-04-13 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_delete_uploadfiles_store_cat_animals_store_cat_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1280, verbose_name='категория по ')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Category_animals',
        ),
        migrations.AlterField(
            model_name='store',
            name='cat_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cat_type', to='store.category_type'),
        ),
    ]
