# Generated by Django 5.0.4 on 2024-04-13 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_category_type_rename_category_category_animals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='cat_animals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cat_animals', to='store.category_animals'),
        ),
        migrations.AlterField(
            model_name='store',
            name='cat_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cat_type', to='store.category_type'),
        ),
    ]
