# Generated by Django 5.0.4 on 2024-04-14 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_store_cat_animals_alter_store_cat_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category_animals',
            new_name='Category',
        ),
        migrations.RemoveField(
            model_name='store',
            name='cat_type',
        ),
        migrations.RemoveField(
            model_name='store',
            name='cat_animals',
        ),
        migrations.AddField(
            model_name='store',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='store.category'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category_type',
        ),
    ]
