# Generated by Django 5.0.4 on 2024-04-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_store_options_store_photo_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='price',
            field=models.CharField(max_length=5, null=True, verbose_name='Цена'),
        ),
    ]
