# Generated by Django 5.0.4 on 2024-04-22 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_store_main_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='main_product',
            field=models.ForeignKey(help_text='Заполняется если текущий продукт является подпродуктом основного, отличаются по весу и т.п', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_products', to='store.store', verbose_name='Основной продукт'),
        ),
    ]
