# Generated by Django 5.0.4 on 2024-04-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_store_main_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='store',
            name='main_product',
        ),
        migrations.AddField(
            model_name='store',
            name='main_product',
            field=models.ManyToManyField(blank=True, help_text='Заполняется если текущий продукт является подпродуктом основного, отличаются по весу и т.п', null=True, related_name='sub_products', to='store.store', verbose_name='Основной продукт'),
        ),
    ]
