# Generated by Django 5.0.4 on 2024-04-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_delete_product_remove_store_main_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='weight',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Вес'),
        ),
    ]
