# Generated by Django 5.0.4 on 2024-04-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_store_taste'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='article',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Артикул'),
        ),
    ]
