# Generated by Django 5.0.4 on 2024-05-03 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_alter_store_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='cat',
        ),
    ]
