# Generated by Django 5.0.4 on 2024-05-03 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_store_tagscats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='tagsCats',
        ),
    ]
