# Generated by Django 5.0.4 on 2024-05-04 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_age_store_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Возраст')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Вид корма',
                'verbose_name_plural': 'Вид корма',
            },
        ),
        migrations.AlterModelOptions(
            name='age',
            options={'verbose_name': 'Возраст', 'verbose_name_plural': 'Возраст'},
        ),
        migrations.AddField(
            model_name='store',
            name='typeFeed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='typeFeed', to='store.typefeed', verbose_name='вид корма'),
        ),
    ]
