# Generated by Django 5.0.4 on 2024-05-04 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_typefeed_alter_age_options_store_typefeed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Возраст')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Размер животного',
                'verbose_name_plural': 'Размер животного',
            },
        ),
        migrations.AddField(
            model_name='store',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='size', to='store.size', verbose_name='Размер животного'),
        ),
    ]
