# Generated by Django 5.0.4 on 2024-05-05 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_alter_store_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=400, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='age',
            field=models.ForeignKey(blank=True, help_text='Заполняется, если есть явное указание на упаковке', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='age', to='store.age', verbose_name='возраст'),
        ),
        migrations.AlterField(
            model_name='store',
            name='size',
            field=models.ForeignKey(blank=True, help_text='Заполняется, если есть явное указание на упаковке', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='size', to='store.size', verbose_name='Размер животного'),
        ),
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(max_length=400, unique=True, verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='store',
            name='taste',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Вкус'),
        ),
        migrations.AlterField(
            model_name='store',
            name='title',
            field=models.CharField(max_length=400, verbose_name='Заголовок'),
        ),
    ]
