# Generated by Django 5.0.4 on 2024-05-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_alter_store_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-title'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RemoveField(
            model_name='store',
            name='size',
        ),
        migrations.AddField(
            model_name='store',
            name='size',
            field=models.ManyToManyField(blank=True, related_name='size', to='store.size', verbose_name='Размер животного'),
        ),
    ]
