# Generated by Django 5.0.4 on 2024-05-25 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_alter_store_options_remove_store_size_store_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='age',
        ),
        migrations.AddField(
            model_name='store',
            name='age',
            field=models.ManyToManyField(blank=True, related_name='size', to='store.age', verbose_name='Возраст'),
        ),
    ]
